const writerOpts = {
  groupBy: "section", // Group commits by their "section" attribute
  commitGroupsSort: "title", // Sort groups by title (section names)
  commitsSort: ["type", "subject"], // Sort commits within each group
  transform: (commit, context) => {
    const typeToSectionMap = {
      feat: "✨ New Features",
      fix: "🐛 Bug Fixes",
      hotfix: "🐛 Bug Fixes",
      chore: "🛠️ Miscellaneous",
      docs: "🛠️ Miscellaneous",
      style: "🛠️ Miscellaneous",
      test: "🛠️ Miscellaneous",
      refactor: "⚠️ Major Changes",
      "BREAKING CHANGE": "⚠️ Major Changes",
    };

    // Assign section based on type
    commit.section = typeToSectionMap[commit.type] || "Other";

    // Map pull request and commit links
    if (commit.pullRequest && commit.pullRequest.number) {
      commit.pullRequestLink = `[PR #${commit.pullRequest.number}](${context.repository}/pull/${commit.pullRequest.number})`;
    }
    if (commit.hash) {
      commit.commitLink = `[${commit.hash.substring(0, 7)}](${context.repository}/commit/${commit.hash})`;
    }

    // Format type for display
    commit.typeFormatted = commit.type.charAt(0).toUpperCase() + commit.type.slice(1);

    return commit;
  },
  mainTemplate: `
    {{> header}}

    {{#each commitGroups}}
      ## {{title}}
      {{#each commits}}
      - {{typeFormatted}}: {{subject}} {{#if pullRequestLink}}({{pullRequestLink}}){{else}}({{commitLink}}){{/if}}
      {{/each}}
    {{/each}}

    {{> footer}}
  `,
  headerPartial: `
    # DekTek Changelog
    All notable changes are listed below.
  `,
  footerPartial: `
    ---
    Generated by Release It!
  `,
};

module.exports = writerOpts;