const writerOpts = {
  partials: {
    features: `
      ## ✨ New Features
      {{#each commits}}
      - {{typeFormatted}}: {{subject}} {{#if pullRequestLink}}({{pullRequestLink}}){{else}}({{commitLink}}){{/if}}
      {{/each}}
    `,
    bugFixes: `
      ## 🐛 Bug Fixes
      {{#each commits}}
      - {{typeFormatted}}: {{subject}} {{#if pullRequestLink}}({{pullRequestLink}}){{else}}({{commitLink}}){{/if}}
      {{/each}}
    `,
    miscellaneous: `
      ## 🛠️ Miscellaneous
      {{#each commits}}
      - {{typeFormatted}}: {{subject}} {{#if pullRequestLink}}({{pullRequestLink}}){{else}}({{commitLink}}){{/if}}
      {{/each}}
    `,
  },
  transform: (commit) => {
    const typeToSectionMap = {
      feat: "features",
      fix: "bugFixes",
      chore: "miscellaneous",
      docs: "miscellaneous",
      style: "miscellaneous",
      test: "miscellaneous",
    };

    commit.section = typeToSectionMap[commit.type] || "miscellaneous"; // Assign section dynamically
    commit.typeFormatted = commit.type.charAt(0).toUpperCase() + commit.type.slice(1);
    return commit;
  },
  groupBy: "section",
  mainTemplate: `
    {{> header}}

    {{#each commitGroups}}
      {{#if (eq title "features")}}
        {{> features}}
      {{/if}}
      {{#if (eq title "bugFixes")}}
        {{> bugFixes}}
      {{/if}}
      {{#if (eq title "miscellaneous")}}
        {{> miscellaneous}}
      {{/if}}
    {{/each}}

    {{> footer}}
  `,
  headerPartial: `
    # DekTek Changelog
    All notable changes are listed below.
  `,
  footerPartial: `
    ---
    Generated by Release It!
  `,
};