name: Generate Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install github-changelog-generator
        run: gem install github_changelog_generator

      - name: Generate CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for API access
        run: github_changelog_generator --user your-username --project your-repo-name

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore: Update CHANGELOG.md"
          git push
