name: Generate Changelog and Tag Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.get-version.outputs.app_version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Extract App Version
        id: get-version
        run: |
          # Extract versionName from build.gradle or build.gradle.kts
          if [ -f app/build.gradle ]; then
            APP_VERSION=$(grep -oP 'versionName\s*"\K[0-9.]+(?=")' app/build.gradle)
          elif [ -f app/build.gradle.kts ]; then
            APP_VERSION=$(grep -oP 'versionName\s*=\s*"\K[0-9.]+(?=")' app/build.gradle.kts)
          else
            echo "No build.gradle or build.gradle.kts file found!"
            exit 1
          fi
          echo "App version: $APP_VERSION"
          echo "::set-output name=app_version::$APP_VERSION"

  tagging:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Check and Create Tag
        env:
          APP_VERSION: ${{ needs.setup.outputs.app_version }}
        run: |
          # Set remote URL to use SSH
          git remote set-url origin git@github.com:your-username/your-repo.git
          
          # Fetch existing tags
          git fetch --tags
          
          # Check if tag exists
          if git rev-parse "v$APP_VERSION" >/dev/null 2>&1; then
            echo "Tag v$APP_VERSION already exists. Exiting."
            exit 0
          fi
          
          # Create and push the new tag
          echo "Creating and pushing tag v$APP_VERSION"
          git tag "v$APP_VERSION"
          git push origin "v$APP_VERSION"

  changelog:
    runs-on: ubuntu-latest
    needs: tagging
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Required Gems
        run: |
          gem install github_changelog_generator
          gem install faraday-retry

      - name: Generate CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: github_changelog_generator --user your-username --project your-repo -t $GITHUB_TOKEN

      - name: Commit and Push Changelog
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore: Update CHANGELOG.md"
          git push
