name: Calculate version, generate changelog and tag

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write  # Ensure the GITHUB_TOKEN has write permissions

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out repository
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 3: Configure credentials
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # Step 4: Calculate version, create tag, and update changelog
      - name: Generate version and changelog
        id: release-it
        run: |
          npx release-it --config release-it.config.js --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Fetch the latest tag created by release-it
      - name: Fetch Latest Tag
        id: fetch_tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      # Step 6: Update VERSION_NAME environment variable
      - name: Update VERSION_NAME Variable
        uses: mmoyaferrer/set-github-variable@v1.0.0
        with:
          name: VERSION_NAME
          value: ${{ env.LATEST_TAG }}
          repository: rikezero/DekTekApp
          token: ${{ secrets.PAT_TOKEN }}