name: Calculate version, generate changelog and tag

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write  # Ensure the GITHUB_TOKEN has write permissions

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION_NAME: ${{ vars.VERSION_NAME }}
    steps:
      # Step 1: Check out repository
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 3: Configure credentials
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # Step 4: Calculate version, create tag, and update changelog
      - name: Generate version and changelog
        id: release-it
        run: |
          npx release-it --config release-it.config.js > release-it-output.txt
          VERSION=$(grep -oP 'Version \K[0-9]+\.[0-9]+\.[0-9]+' release-it-output.txt)
          echo "Extracted version: $VERSION"
          echo "VERSION_NAME=$VERSION" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Update VERSION_NAME Repository Variable
      - name: Update VERSION_NAME Variable
        uses: mmoyaferrer/set-github-variable@v1.0.0
        with:
          name: VERSION_NAME
          value: ${{ env.VERSION_NAME }}
          repository: rikezero/DekTekApp
          token: ${{ secrets.PAT_TOKEN }}