name: Convert SVG to Android XML

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,16 * *'

jobs:
  #
  # 1) Install Node, clone mtg-vectors, recursively find & convert SVGs with s2v, upload results
  #
  convert-svgs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install svg2vectordrawable globally
        run: |
          npm install --global svg2vectordrawable
          s2v -h

      - name: Clone mtg-vectors repository
        run: git clone https://github.com/Investigamer/mtg-vectors.git

      - name: Convert SVGs (recursively) to XML
        run: |
          INPUT_DIR="mtg-vectors/svg/optimized/set"
          OUTPUT_DIR="converted"
          mkdir -p "$OUTPUT_DIR"

          # Check if at least one *.svg exists under INPUT_DIR
          if ! find "$INPUT_DIR" -type f -name "*.svg" | grep -q .; then
            echo "No SVG files found under $INPUT_DIR (including subfolders)."
            exit 0  # Exit gracefully, no SVGs to process
          fi

          echo "Converting all SVGs found under $INPUT_DIR ..."

          # Recursively find all .svg files, convert each separately
          find "$INPUT_DIR" -type f -name "*.svg" | while read -r SVG_FILE; do
            # Extract the folder name
            FOLDER_NAME=$(basename "$(dirname "$SVG_FILE")" | tr '[:upper:]' '[:lower:]')
            # Extract the base file name
            BASE_NAME=$(basename "$SVG_FILE" .svg | tr '[:upper:]' '[:lower:]')

            # Combine folder name + base name into the output file name
            OUTPUT_FILE="$OUTPUT_DIR/ic_set_${FOLDER_NAME}_${BASE_NAME}.xml"

            # Use s2v for conversion:
            s2v -i "$SVG_FILE" -o "$OUTPUT_FILE"
          done

      - name: Upload converted vectors
        uses: actions/upload-artifact@v3
        with:
          name: converted-vectors
          path: converted

  #
  # 2) Check out DekTekApp via SSH, update resources, commit, and push
  #
  update-dektek-resources:
    runs-on: ubuntu-latest
    needs: [convert-svgs]
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Download converted files
        uses: actions/download-artifact@v3
        with:
          name: converted-vectors
          path: converted

      - name: Clone DekTekApp repository (SSH)
        run: |
          git clone git@github.com:rikezero/DekTekApp.git
          cd DekTekApp
          git checkout main
          git pull origin main
          cd ..

      - name: Copy new/updated XML files into resources
        run: |
          RESOURCE_DIR="DekTekApp/app/src/main/res/drawable"
          mkdir -p "$RESOURCE_DIR"

          for XML_FILE in converted/*.xml; do
            [ -e "$XML_FILE" ] || continue

            BASENAME=$(basename "$XML_FILE")
            TARGET_FILE="$RESOURCE_DIR/$BASENAME"

            # If target exists, compare; if different, overwrite
            if [ -f "$TARGET_FILE" ]; then
              if ! cmp -s "$XML_FILE" "$TARGET_FILE"; then
                cp "$XML_FILE" "$TARGET_FILE"
              fi
            else
              cp "$XML_FILE" "$TARGET_FILE"
            fi
          done

      - name: Commit and push changes with timestamp
        run: |
          cd DekTekApp
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Capture the current date in dd/mm/YYYY format
          COMMIT_DATE=$(date +%d/%m/%Y)

          # Check if there are any changes
          if [ -n "$(git status --porcelain)" ]; then
            git add app/src/main/res/drawable/*.xml
            git commit -m "chore: update sets vector assets as of ${COMMIT_DATE}"
            git push origin main
          else
            echo "No changes to commit."