name: Convert SVG to Android XML

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,16 * *'

jobs:
  #
  # 1) Convert SVGs with s2v (svg2vectordrawable), upload as artifact
  #
  convert-svgs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install svg2vectordrawable globally
        run: |
          npm install --global svg2vectordrawable
          s2v -h

      - name: Clone mtg-vectors repository
        run: git clone https://github.com/Investigamer/mtg-vectors.git

      - name: Convert SVGs (recursively) to XML
        run: |
          INPUT_DIR="mtg-vectors/svg/optimized/set"
          OUTPUT_DIR="converted"
          mkdir -p "$OUTPUT_DIR"

          if ! find "$INPUT_DIR" -type f -name "*.svg" | grep -q .; then
            echo "No SVG files found under $INPUT_DIR. Exiting gracefully."
            exit 0
          fi

          echo "Converting all SVGs found under $INPUT_DIR ..."
          find "$INPUT_DIR" -type f -name "*.svg" | while read -r SVG_FILE; do
            FOLDER_NAME=$(basename "$(dirname "$SVG_FILE")" | tr '[:upper:]' '[:lower:]')
            BASE_NAME=$(basename "$SVG_FILE" .svg | tr '[:upper:]' '[:lower:]')
            OUTPUT_FILE="$OUTPUT_DIR/ic_set_${FOLDER_NAME}_${BASE_NAME}.xml"

            s2v -i "$SVG_FILE" -o "$OUTPUT_FILE"
          done

      - name: Upload converted vectors
        uses: actions/upload-artifact@v3
        with:
          name: converted-vectors
          path: converted

  #
  # 2) Clone DekTekApp, copy changes, create a PR using actions/create-pull-request
  #
  update-dektek-resources:
    runs-on: ubuntu-latest
    needs: [convert-svgs]
    steps:
      - name: Download converted files
        uses: actions/download-artifact@v3
        with:
          name: converted-vectors
          path: converted

      # This checks out your DekTekApp repo into the current working directory
      - name: Check out DekTekApp repository
        uses: actions/checkout@v3
        with:
          repository: rikezero/DekTekApp
          token: ${{ secrets.GITHUB_TOKEN }}  # or a PAT with 'repo' scope
          ref: main  # checkout the main branch by default
          path: DekTekApp

      - name: Copy new/updated XML files into resources
        run: |
          RESOURCE_DIR="DekTekApp/app/src/main/res/drawable"
          mkdir -p "$RESOURCE_DIR"

          for XML_FILE in converted/*.xml; do
            [ -e "$XML_FILE" ] || continue
            BASENAME=$(basename "$XML_FILE")
            TARGET_FILE="$RESOURCE_DIR/$BASENAME"

            # If target exists, compare; if different, overwrite
            if [ -f "$TARGET_FILE" ]; then
              if ! cmp -s "$XML_FILE" "$TARGET_FILE"; then
                cp "$XML_FILE" "$TARGET_FILE"
              fi
            else
              cp "$XML_FILE" "$TARGET_FILE"
            fi
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          # The branch name that will be created for the PR
          branch: 'chore/auto-update-vectors'
          base: 'master'
          title: 'chore: update set vectors'
          body: 'This PR updates the set vector assets in the app/src/main/res/drawable folder.'
          labels: 'automerge'
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: 'chore: update sets vector assets as of $CURRENT_DATE'
          committer: 'GitHub Actions <actions@github.com>'
          author: 'GitHub Actions <actions@github.com>'
          delete-branch: true
          signoff: false