name: Convert SVG to Android XML

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,16 * *'

jobs:
  #
  # 1) Install Python, clone svg2vectordrawable & mtg-vectors, convert SVGs, and upload results
  #
  convert-svgs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository (if needed)
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Clone and install svg2vectordrawable from source
      - name: Clone svg2vectordrawable
        run: git clone https://github.com/Ashung/svg2vectordrawable.git

      - name: Install svg2vectordrawable locally
        run: |
          cd svg2vectordrawable
          pip install .

      - name: Clone mtg-vectors repository
        run: |
          git clone https://github.com/Investigamer/mtg-vectors.git

      - name: Convert SVGs to Android XML
        run: |
          INPUT_DIR="mtg-vectors/svg/optimized/set"
          OUTPUT_DIR="converted"

          mkdir -p "$OUTPUT_DIR"

          # Loop through all SVG files in the set directory
          for SVG_FILE in "$INPUT_DIR"/*.svg; do
            BASENAME=$(basename "$SVG_FILE" .svg | tr '[:upper:]' '[:lower:]')
            OUTPUT_FILE="$OUTPUT_DIR/ic_set_${BASENAME}.xml"

            # Convert using svg2vectordrawable
            svg2vectordrawable "$SVG_FILE" "$OUTPUT_FILE"
          done

      - name: Upload converted vectors
        uses: actions/upload-artifact@v3
        with:
          name: converted-vectors
          path: converted

  #
  # 2) Check out DekTekApp via SSH, update resources, commit, and push
  #
  update-dektek-resources:
    runs-on: ubuntu-latest
    needs: [convert-svgs]
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Download converted files
        uses: actions/download-artifact@v3
        with:
          name: converted-vectors
          path: converted

      - name: Clone DekTekApp repository (SSH)
        run: |
          git clone git@github.com:rikezero/DekTekApp.git
          cd DekTekApp
          git checkout main
          git pull origin main
          cd ..

      - name: Copy new/updated XML files into resources
        run: |
          RESOURCE_DIR="DekTekApp/app/src/main/res/drawable"
          mkdir -p "$RESOURCE_DIR"

          for XML_FILE in converted/*.xml; do
            BASENAME=$(basename "$XML_FILE")
            TARGET_FILE="$RESOURCE_DIR/$BASENAME"

            # If target exists, compare; if different, overwrite
            if [ -f "$TARGET_FILE" ]; then
              if ! cmp -s "$XML_FILE" "$TARGET_FILE"; then
                cp "$XML_FILE" "$TARGET_FILE"
              fi
            else
              cp "$XML_FILE" "$TARGET_FILE"
            fi
          done

      - name: Commit and push changes with timestamp
        run: |
          cd DekTekApp
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Capture the current date in dd/mm/YYYY format
          COMMIT_DATE=$(date +%d/%m/%Y)

          # Check if there are any changes
          if [ -n "$(git status --porcelain)" ]; then
            git add app/src/main/res/drawable/*.xml
            git commit -m "chore: update sets vector assets as of ${COMMIT_DATE}"
            git push origin main
          else
            echo "No changes to commit."
