update-dektek-resources:
  runs-on: ubuntu-latest
  needs: [convert-svgs]
  steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    - name: Download converted files
      uses: actions/download-artifact@v3
      with:
        name: converted-vectors
        path: converted

    - name: Clone DekTekApp repository (SSH)
      run: |
        git clone git@github.com:rikezero/DekTekApp.git
        cd DekTekApp
        git checkout main
        git pull origin main
        cd ..

    - name: Copy new/updated XML files into resources
      run: |
        RESOURCE_DIR="DekTekApp/app/src/main/res/drawable"
        mkdir -p "$RESOURCE_DIR"
        
        for XML_FILE in converted/*.xml; do
          BASENAME=$(basename "$XML_FILE")
          TARGET_FILE="$RESOURCE_DIR/$BASENAME"
        
          # If target exists, compare; if different, overwrite
          if [ -f "$TARGET_FILE" ]; then
            if ! cmp -s "$XML_FILE" "$TARGET_FILE"; then
              cp "$XML_FILE" "$TARGET_FILE"
            fi
          else
            cp "$XML_FILE" "$TARGET_FILE"
          fi
        done

    - name: Commit and push changes with timestamp
      run: |
        cd DekTekApp
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        # Capture the current date in dd/mm/YYYY format
        COMMIT_DATE=$(date +%d/%m/%Y)
        
        # Check if there are any changes
        if [ -n "$(git status --porcelain)" ]; then
          git add app/src/main/res/drawable/*.xml
          git commit -m "chore: update sets vector assets as of ${COMMIT_DATE}"
          git push origin main
        else
          echo "No changes to commit."
        fi