name: Convert SVG to Android XML and Create PR

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,16 * *'  # Runs on the 1st and 16th of every month at midnight UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  convert-svgs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install svg2vectordrawable globally
        run: |
          npm install --global svg2vectordrawable
          s2v -h  # Verify installation

      - name: Clone mtg-vectors repository
        run: git clone https://github.com/Investigamer/mtg-vectors.git

      - name: Convert SVGs to XML
        run: |
          INPUT_DIR="mtg-vectors/svg/optimized/set"
          OUTPUT_DIR="converted"
          mkdir -p "$OUTPUT_DIR"

          # Check if SVG files exist
          if ! find "$INPUT_DIR" -type f -name "*.svg" | grep -q .; then
            echo "No SVG files found under $INPUT_DIR. Exiting gracefully."
            exit 0
          fi

          echo "Converting all SVGs found under $INPUT_DIR ..."
          find "$INPUT_DIR" -type f -name "*.svg" | while read -r SVG_FILE; do
            FOLDER_NAME=$(basename "$(dirname "$SVG_FILE")" | tr '[:upper:]' '[:lower:]')
            BASE_NAME=$(basename "$SVG_FILE" .svg | tr '[:upper:]' '[:lower:]')
            OUTPUT_FILE="$OUTPUT_DIR/ic_set_${FOLDER_NAME}_${BASE_NAME}.xml"

            s2v -i "$SVG_FILE" -o "$OUTPUT_FILE"
          done

      - name: Upload converted vectors
        uses: actions/upload-artifact@v4
        with:
          name: converted-vectors
          path: converted

  update-dektek-resources:
    runs-on: ubuntu-latest
    needs: convert-svgs
    steps:
      - name: Download converted vectors
        uses: actions/download-artifact@v4
        with:
          name: converted-vectors
          path: converted

      - name: Set CURRENT_DATE
        run: echo "CURRENT_DATE=$(date +'%d/%m/%Y')" >> $GITHUB_ENV

      - name: Check out DekTekApp repository
        uses: actions/checkout@v4
        with:
          repository: rikezero/DekTekApp
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Create a new branch from master
        run: git checkout -b chore/auto-update-vectors

      - name: Copy converted XML files into DekTekApp
        run: |
          RESOURCE_DIR="app/src/main/res/drawable"
          mkdir -p "$RESOURCE_DIR"

          for XML_FILE in converted/*.xml; do
            [ -e "$XML_FILE" ] || continue  # Skip if no files
            BASENAME=$(basename "$XML_FILE")
            TARGET_FILE="$RESOURCE_DIR/$BASENAME"

            # Overwrite if file exists and is different
            if [ -f "$TARGET_FILE" ]; then
              if ! cmp -s "$XML_FILE" "$TARGET_FILE"; then
                cp "$XML_FILE" "$TARGET_FILE"
                echo "Updated $TARGET_FILE"
              fi
            else
              cp "$XML_FILE" "$TARGET_FILE"
              echo "Added $TARGET_FILE"
            fi
          done

      - name: Verify changes, commit, and push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          if git diff --quiet; then
          echo "No changes to commit."
          else
          git add .
          git commit -m "chore: auto-update vectors"
          git push origin chore/auto-update-vectors
          fi     

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: 'master'
          title: 'chore: update set vectors'
          body: |
            This PR updates the set vector assets in the app/src/main/res/drawable folder.
          labels: 'automerge'
          delete-branch: true
          draft: false
          signoff: false
          sign-commits: false
          maintainer-can-modify: true