name: Automatic Versioning

on:
  push:
    branches:
      - master
      - dev
      - 'feature/**'
      - 'fix/**'
      - 'hotfix/**'

permissions:
  actions: write  # Grants write permissions to the actions scope, including variables

jobs:
  update-version:
    if: github.actor != 'github-actions[bot]'  # Prevents the workflow from running on its own commits
    name: Calculate and Update VERSION_NAME
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Repository with Full History
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necessary for GitVersion to access full history

      # Step 2: Prevent Workflow Loop on Version Bump Commits
      - name: Prevent Loop on Version Bump Commits
        if: "startsWith(github.head_commit.message, 'chore: bump version to')"
        run: |
          echo "Detected version bump commit. Exiting workflow to prevent loop."
          exit 0

      # Step 3: Set Up SSH Authentication
      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 4: Install GitVersion
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.x'  # Specify the GitVersion version or use 'latest' for the latest version

      # Step 5: Run GitVersion and Output JSON
      - name: Run GitVersion
        id: gitversion
        run: gitversion /output json > gitversion.json

      # Step 6: Extract GitVersion Outputs
      - name: Extract GitVersion Outputs
        id: extract_version
        run: |
          VERSION_NAME=$(jq -r '.SemVer' gitversion.json)
          MAJOR=$(jq -r '.Major' gitversion.json)
          MINOR=$(jq -r '.Minor' gitversion.json)
          PATCH=$(jq -r '.Patch' gitversion.json)
          VERSION_CODE=$((MAJOR * 10000 + MINOR * 100 + PATCH))
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV
          echo "VERSION_CODE=${VERSION_CODE}" >> $GITHUB_ENV
        shell: bash

      # Step 7: Update VERSION_NAME Repository Variable via GitHub API
      - name: Update VERSION_NAME Variable
        run: |
          # Install jq if not already available
          sudo apt-get update && sudo apt-get install -y jq

          API_URL="https://api.github.com/repos/${{ github.repository }}/actions/variables/VERSION_NAME"
          NEW_VERSION="${VERSION_NAME}"

          # Fetch the current variable ID
          VARIABLE_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/variables" | \
            jq -r --arg name "VERSION_NAME" '.variables[] | select(.name==$name) | .id')

          if [ -z "$VARIABLE_ID" ]; then
            echo "VERSION_NAME variable not found. Creating it."
            CREATE_RESPONSE=$(curl -s -X POST "https://api.github.com/repos/${{ github.repository }}/actions/variables" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              -d "{\"name\": \"VERSION_NAME\", \"value\": \"${NEW_VERSION}\"}")

            UPDATED_VALUE=$(echo "$CREATE_RESPONSE" | jq -r '.value')
            if [ "$UPDATED_VALUE" == "$NEW_VERSION" ]; then
              echo "VERSION_NAME successfully created with value ${NEW_VERSION}"
            else
              echo "Failed to create VERSION_NAME. Response:"
              echo "$CREATE_RESPONSE"
              exit 1
            fi
          else
            # Update existing variable
            RESPONSE=$(curl -s -X PATCH "$API_URL/$VARIABLE_ID" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              -d "{\"value\": \"${NEW_VERSION}\"}")

            # Validate the response
            UPDATED_VALUE=$(echo "$RESPONSE" | jq -r '.value')
            if [ "$UPDATED_VALUE" == "$NEW_VERSION" ]; then
              echo "VERSION_NAME successfully updated to ${NEW_VERSION}"
            else
              echo "Failed to update VERSION_NAME. Response:"
              echo "$RESPONSE"
              exit 1
            fi
          fi
        shell: bash

      # Optional Step 8: Create a Git Tag for the New Version
      - name: Create Git Tag
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        run: |
          git tag -a "v${VERSION_NAME}" -m "Release version ${VERSION_NAME}"
          git push origin "v${VERSION_NAME}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional Step 9: Create GitHub Release
      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${VERSION_NAME}"
          release_name: "Release v${VERSION_NAME}"
          body: "Automated release for version v${VERSION_NAME}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
